// Generated by gen_site.py: blocks /download/ while downloads are switched off
// (with /downloads in the bot). Asks the FISCHXR service at most every 30 seconds.
const SERVICE = "https://fischxr-api.exoartar.workers.dev";
let cache = { at: 0, value: null };
const esc = (t) => String(t).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
export async function onRequest(context) {
  try {
    if (!cache.value || Date.now() - cache.at > 30000) {
      const r = await fetch(SERVICE + "/site", { cf: { cacheTtl: 0 } });
      cache = { at: Date.now(), value: r.ok ? await r.json() : null };
    }
    const d = cache.value && cache.value.downloads;
    if (d && d.enabled === false) {
      const msg = esc(d.message || "FISCHXR downloads are switched off for now. Check the Discord for news.");
      return new Response('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Downloads paused</title>'
        + '<body style="margin:0;min-height:100vh;display:grid;place-items:center;background:#000;color:#fff;font:16px/1.6 system-ui,sans-serif;text-align:center;padding:24px">'
        + '<div><h1 style="font-size:32px;margin:0 0 10px">Downloads are paused</h1><p style="color:#9A9A9A;max-width:46ch;margin:0 auto">' + msg + '</p></div></body>',
        { status: 503, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
    }
  } catch (e) { /* the service can't be reached: don't block downloads */ }
  return context.next();
}
